using System.ComponentModel.DataAnnotations;

namespace CrashVisualizer.Models
{
    public enum UsaStateName
    {
        Alabama,
        Alaska                   ,
        Arizona,
        Arkansas                 ,
        California               ,
        Colorado                 ,
        Connecticut              ,
        Delaware                 ,
        Florida                  ,
        Georgia                  ,
        Hawaii                   ,
        Idaho                    ,
        IllinoisIndiana          ,
        Iowa                     ,
        Kansas                   ,
        Kentucky                 ,
        Louisiana                ,
        Maine                    ,
        Maryland                 ,
        Massachusetts            ,
        Michigan                 ,
        Minnesota                ,
        Mississippi              ,
        Missouri                 ,
        Montana,
        Nebraska          ,
        Nevada                   ,
        NewHampshire            ,
        NewJersey               ,
        NewMexico               ,
        NewYork                 ,
        NorthCarolina           ,
        NorthDakota             ,
        Ohio                     ,
        Oklahoma                 ,
        Oregon                   ,
        PennsylvaniaRhodeIsland ,
        [Display(Name = "South Carolina")]
        SouthCarolina           ,
        SouthDakota             ,
        Tennessee                ,
        Texas                    ,
        Utah                     ,
        Vermont                  ,
        Virginia                 ,
        Washington               ,
        WestVirginia            ,
        Wisconsin                ,
        Wyoming                  ,
    }
}
